// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJUKGYGXhAZZK14rZRBX-DDqeJa0pD5no',
    appId: '1:26184870649:android:bac901ff1f711ea0621028',
    messagingSenderId: '26184870649',
    projectId: 'flutter-video-audio-chat-baf9c',
    storageBucket: 'flutter-video-audio-chat-baf9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiCJLksNR9W6JX8tbPJqFJvslcDj8efq4',
    appId: '1:26184870649:ios:887a732db7bd11ce621028',
    messagingSenderId: '26184870649',
    projectId: 'flutter-video-audio-chat-baf9c',
    storageBucket: 'flutter-video-audio-chat-baf9c.appspot.com',
    androidClientId: '26184870649-b1mlsp1oiasftuofl0eukokl9q37b4hu.apps.googleusercontent.com',
    iosClientId: '26184870649-3j2fidhsv1tha338tds9tnu8e7bakmvk.apps.googleusercontent.com',
    iosBundleId: 'com.thanasarn.rich.rich',
  );
}
